# Generated by Django 4.2.7 on 2024-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
