# Generated by Django 4.2.1 on 2023-05-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='fk_traslation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='word.translation'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
