# Generated by Django 4.2.1 on 2023-09-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='gpt_identifier',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='pronunciation',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='reference',
        ),
    ]
