# Generated by Django 4.2.1 on 2023-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_fk_traslation_alter_word_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
