# Generated by Django 4.2.15 on 2024-08-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0009_wordmemorizationrandomtest_needs_reinforcement'),
        ('word', '0002_alter_tags_term'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='Terms',
            new_name='Term',
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='Token',
        ),
    ]
