# Generated by Django 4.2.6 on 2023-12-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_terms_language_alter_terms_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('term', 'reference')},
        ),
    ]
