# Generated by Django 4.2.18 on 2025-03-04 18:18

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_rename_tags_tag_rename_terms_term_rename_word_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTexts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', ckeditor.fields.RichTextField()),
                ('scrambled_text', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(upload_to='audios/')),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='short_texts_word_tags', to='word.tag')),
            ],
        ),
    ]
