# Generated by Django 4.2.18 on 2025-03-04 18:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_shorttexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttexts',
            name='scrambled_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
