# Generated by Django 4.2.6 on 2023-12-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_translation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('term', 'reference', 'language')},
        ),
    ]
