# Generated by Django 4.2.1 on 2023-05-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_grammaticalclasses_alter_translation_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='fk_traslation',
        ),
        migrations.AddField(
            model_name='word',
            name='fk_traslation',
            field=models.ManyToManyField(blank=True, null=True, related_name='translation', to='word.translation'),
        ),
    ]
