# Generated by Django 4.2.7 on 2023-12-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_alter_translation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together=set(),
        ),
    ]
