# Generated by Django 4.2.18 on 2025-03-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_alter_shorttexts_scrambled_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortTexts',
            new_name='ShortText',
        ),
    ]
