# Generated by Django 4.2.1 on 2023-05-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_remove_word_fk_traslation_word_fk_traslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='./audios'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='terms',
            field=models.TextField(),
        ),
    ]
