# Generated by Django 4.2.18 on 2025-03-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_rename_shorttexts_shorttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttext',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
