# Generated by Django 4.2.18 on 2025-03-23 21:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_alter_shorttext_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='translate',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
