# Generated by Django 4.2.1 on 2023-05-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_alter_phrase_pronunciation_alter_phrase_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation', models.FileField(blank=True, null=True, upload_to='./audios')),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='pronunciation',
        ),
        migrations.AlterField(
            model_name='word',
            name='fk_traslation',
            field=models.ManyToManyField(blank=True, null=True, related_name='word_translation', to='word.translation'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='pronunciation',
        ),
        migrations.AddField(
            model_name='phrase',
            name='pronunciation',
            field=models.ManyToManyField(blank=True, null=True, related_name='phrase_pronunciation', to='word.pronunciation'),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.ManyToManyField(blank=True, null=True, related_name='word_pronunciation', to='word.pronunciation'),
        ),
    ]
