# Generated by Django 4.2.7 on 2024-05-28 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_alter_tags_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
    ]
