# Generated by Django 4.2.1 on 2023-05-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_remove_audiowordmemorizationtest_audio_and_more'),
        ('word', '0008_pronunciation_remove_phrase_pronunciation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='pronunciation',
        ),
        migrations.AlterField(
            model_name='word',
            name='fk_traslation',
            field=models.ManyToManyField(blank=True, null=True, related_name='translation', to='word.translation'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='pronunciation',
        ),
        migrations.DeleteModel(
            name='Pronunciation',
        ),
        migrations.AddField(
            model_name='phrase',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='./audios'),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='./audios'),
        ),
    ]
