# Generated by Django 4.2.18 on 2025-03-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_shorttext_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
