# Generated by Django 4.2.1 on 2023-05-17 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_remove_phrase_pronunciation_alter_word_fk_traslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='phrase_tags', to='word.tags'),
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='word_tags', to='word.tags'),
        ),
    ]
