# Generated by Django 4.2.18 on 2025-03-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_shorttext_completed_shorttext_running'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorttext',
            old_name='running',
            new_name='has_audio',
        ),
    ]
