# Generated by Django 4.2.7 on 2024-06-02 21:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_wordterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=4000),
        ),
    ]
