# Generated by Django 4.2.7 on 2024-06-02 21:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_alter_terms_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
