# Generated by Django 4.2.18 on 2025-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_rename_running_shorttext_has_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='has_translate',
            field=models.BooleanField(default=False),
        ),
    ]
