# Generated by Django 4.2.1 on 2023-05-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0011_alter_translation_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='fk_traslation',
            new_name='traslation',
        ),
    ]
