# Generated by Django 4.2.20 on 2025-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0011_shorttext_has_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='right_option',
            field=models.BooleanField(default=False),
        ),
    ]
