# Generated by Django 4.2.1 on 2023-05-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0012_rename_fk_traslation_word_traslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='traslation',
            new_name='translation',
        ),
    ]
