# Generated by Django 4.2.20 on 2025-06-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0012_translation_right_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordterm',
            name='term',
        ),
        migrations.RemoveField(
            model_name='wordterm',
            name='word',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='WordTerm',
        ),
    ]
