# Generated by Django 4.2.1 on 2023-05-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0013_rename_traslation_word_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='translation',
        ),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, null=True, to='word.translation'),
        ),
    ]
