# Generated by Django 4.2.25 on 2025-10-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0014_historyattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryAttempt',
        ),
    ]
