# Generated by Django 4.2.1 on 2023-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0015_rename_fk_translation_phrase_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, null=True, related_name='word_translations', to='word.translation'),
        ),
    ]
