# Generated by Django 4.2.25 on 2025-11-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0015_delete_historyattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttext',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='shorttext',
            name='has_audio',
        ),
        migrations.RemoveField(
            model_name='shorttext',
            name='has_translate',
        ),
        migrations.RemoveField(
            model_name='shorttext',
            name='scrambled_text',
        ),
        migrations.RemoveField(
            model_name='shorttext',
            name='translate',
        ),
        migrations.AddField(
            model_name='shorttext',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.term'),
        ),
    ]
