# Generated by Django 4.2.25 on 2025-11-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0016_remove_shorttext_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttext',
            name='reference',
        ),
    ]
