# Generated by Django 4.2.1 on 2023-05-23 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0016_alter_word_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('pronunciation', models.FileField(blank=True, null=True, upload_to='./audios')),
                ('obs', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='word_tags', to='word.tags')),
                ('terms', models.ManyToManyField(blank=True, null=True, to='word.terms')),
                ('translations', models.ManyToManyField(blank=True, null=True, related_name='word_translations', to='word.translation')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translations',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
