# Generated by Django 4.2.1 on 2023-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0017_terms_remove_word_tags_remove_word_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
