# Generated by Django 4.2.25 on 2025-11-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0017_remove_shorttext_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.shorttext'),
        ),
    ]
