# Generated by Django 4.2.1 on 2023-05-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0018_alter_terms_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='term',
            field=models.TextField(),
        ),
    ]
