# Generated by Django 4.2.25 on 2025-11-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0018_term_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translation',
            new_name='Options',
        ),
    ]
