# Generated by Django 4.2.1 on 2023-05-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0019_alter_translation_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='term',
            field=models.TextField(),
        ),
    ]
