# Generated by Django 4.2.25 on 2025-11-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0019_rename_translation_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
    ]
