# Generated by Django 5.0.6 on 2025-11-23 16:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0020_rename_options_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='instruction_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='phonetic_transcription_Portuguese',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='translation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
