# Generated by Django 4.2.1 on 2023-05-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0021_remove_terms_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.terms'),
        ),
    ]
