# Generated by Django 5.0.6 on 2025-11-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0021_shorttext_instruction_ia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorttext',
            old_name='phonetic_transcription_Portuguese',
            new_name='phonetic_transcription_portuguese',
        ),
    ]
