# Generated by Django 5.0.6 on 2025-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0022_rename_phonetic_transcription_portuguese_shorttext_phonetic_transcription_portuguese'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
