# Generated by Django 4.2.1 on 2023-05-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0023_terms_gpt_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='word.tags'),
        ),
    ]
