# Generated by Django 5.0.6 on 2025-11-23 18:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0023_shorttext_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttext',
            name='instruction_ia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
