# Generated by Django 4.2.1 on 2023-06-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0024_tags_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='translations',
        ),
        migrations.AddField(
            model_name='translation',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.terms'),
        ),
    ]
