# Generated by Django 5.0.6 on 2025-11-26 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0024_alter_shorttext_instruction_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStudyTimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
