# Generated by Django 4.2.1 on 2023-06-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0025_remove_terms_translations_translation_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms',
            old_name='reference',
            new_name='child',
        ),
    ]
