# Generated by Django 5.0.6 on 2025-11-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0025_totalstudytimelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalstudytimelog',
            name='logout_time',
        ),
    ]
