# Generated by Django 5.0.6 on 2025-11-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0026_remove_totalstudytimelog_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstudytimelog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
