# Generated by Django 4.2.1 on 2023-06-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0026_rename_reference_terms_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms',
            old_name='child',
            new_name='reference',
        ),
    ]
