# Generated by Django 5.0.6 on 2025-11-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0027_totalstudytimelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstudytimelog',
            name='session_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
