# Generated by Django 4.2.1 on 2023-06-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0027_rename_child_terms_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='language',
            field=models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50),
        ),
    ]
