# Generated by Django 4.2.1 on 2023-06-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0028_alter_tags_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('term',)},
        ),
    ]
