# Generated by Django 4.2.1 on 2023-07-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0029_alter_tags_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terms',
            unique_together={('text', 'created_at')},
        ),
    ]
