# Generated by Django 5.0.6 on 2025-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0030_totalstudytimelog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
