# Generated by Django 5.0.6 on 2025-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0031_shorttext_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
