# Generated by Django 5.0.6 on 2026-01-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0032_shorttext_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttext',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
