# Generated by Django 4.2.1 on 2023-05-17 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0007_alter_phrase_pronunciation_alter_phrase_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMemorizationTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('hit_percentage', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traslation', models.ManyToManyField(blank=True, null=True, related_name='word_memorization_translation', to='word.translation')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_memorization_word', to='word.word')),
            ],
        ),
    ]
