# Generated by Django 4.2.1 on 2023-09-14 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('writing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='challenges_tags', to='word.tags')),
            ],
        ),
        migrations.CreateModel(
            name='WordMemorizationRandomTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100)),
                ('term', models.TextField(blank=True, null=True)),
                ('lissen', models.FileField(blank=True, null=True, upload_to='')),
                ('answer', models.TextField(blank=True, null=True)),
                ('hit_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge')),
            ],
        ),
    ]
