# Generated by Django 4.2.1 on 2023-09-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmemorizationrandomtest',
            name='lissen',
        ),
    ]
