# Generated by Django 4.2.1 on 2023-05-17 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_pronunciation_remove_phrase_pronunciation_and_more'),
        ('memorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordMemorizationTest',
            new_name='WritingWordMemorizationTest',
        ),
        migrations.CreateModel(
            name='AudioWordMemorizationTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('hit_percentage', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traslation', models.ManyToManyField(blank=True, null=True, related_name='audio_memorization_translation', to='word.translation')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_memorization_word', to='word.word')),
            ],
        ),
    ]
