# Generated by Django 4.2.1 on 2023-05-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_pronunciation_remove_phrase_pronunciation_and_more'),
        ('memorization', '0002_rename_wordmemorizationtest_writingwordmemorizationtest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiowordmemorizationtest',
            name='traslation',
        ),
        migrations.RemoveField(
            model_name='writingwordmemorizationtest',
            name='traslation',
        ),
        migrations.AddField(
            model_name='audiowordmemorizationtest',
            name='audio',
            field=models.ManyToManyField(blank=True, null=True, related_name='audio_memorization_pronunciation', to='word.pronunciation'),
        ),
        migrations.AddField(
            model_name='writingwordmemorizationtest',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
