# Generated by Django 4.2.7 on 2024-08-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0002_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='challenge',
            new_name='word_memorization_random_test',
        ),
    ]
