# Generated by Django 4.2.1 on 2023-05-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_remove_audiowordmemorizationtest_traslation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiowordmemorizationtest',
            name='audio',
        ),
        migrations.AddField(
            model_name='audiowordmemorizationtest',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
