# Generated by Django 4.2.7 on 2024-08-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_rename_challenge_options_word_memorization_random_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmemorizationrandomtest',
            name='answer',
        ),
    ]
