# Generated by Django 4.2.5 on 2023-09-29 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_remove_challenge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmemorizationrandomtest',
            name='term',
            field=ckeditor.fields.RichTextField(default=3),
            preserve_default=False,
        ),
    ]
