# Generated by Django 4.2.7 on 2024-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_remove_wordmemorizationrandomtest_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
