# Generated by Django 4.2.1 on 2023-05-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_remove_audiowordmemorizationtest_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingwordmemorizationtest',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writingwordmemorizationtest',
            name='hit_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
