# Generated by Django 4.2.5 on 2023-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_alter_wordmemorizationrandomtest_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50),
        ),
    ]
