# Generated by Django 4.2.1 on 2023-05-21 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0005_alter_writingwordmemorizationtest_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTIssues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
