# Generated by Django 4.2.7 on 2024-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0005_alter_options_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
