# Generated by Django 4.2.1 on 2023-05-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0006_gptissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptissues',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
