# Generated by Django 4.2.7 on 2024-08-13 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
        ('memorization', '0007_unavailableitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailableitem',
            name='word_memorization_random_test',
        ),
        migrations.AddField(
            model_name='unavailableitem',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.terms'),
        ),
    ]
