# Generated by Django 4.2.6 on 2023-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0007_challenge_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_correct_answers', models.PositiveIntegerField(default=10)),
                ('correct_percentage_considered', models.PositiveIntegerField(default=80)),
                ('random', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
