# Generated by Django 4.2.6 on 2023-11-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0008_historicchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicchallenge',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge'),
        ),
    ]
