# Generated by Django 4.2.7 on 2024-08-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0008_remove_unavailableitem_word_memorization_random_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmemorizationrandomtest',
            name='needs_reinforcement',
            field=models.BooleanField(default=False),
        ),
    ]
