# Generated by Django 4.2.18 on 2025-03-04 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_alter_shorttext_audio'),
        ('memorization', '0009_wordmemorizationrandomtest_needs_reinforcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeShortText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('writing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_texts', models.ManyToManyField(blank=True, null=True, to='word.shorttext')),
            ],
        ),
    ]
