# Generated by Django 4.2.1 on 2023-05-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0009_wordmemorizationtest_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmemorizationtest',
            name='counter',
        ),
    ]
