# Generated by Django 4.2.18 on 2025-03-04 19:38

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0010_challengeshorttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTextMemorizationTests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scrambled_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
