# Generated by Django 4.2.1 on 2023-05-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0021_remove_terms_terms'),
        ('memorization', '0010_remove_wordmemorizationtest_counter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenges',
            new_name='Challenge',
        ),
        migrations.AddField(
            model_name='wordmemorizationtest',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge'),
        ),
    ]
