# Generated by Django 4.2.6 on 2023-11-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0010_historicchallenge_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='correct_percentage_considered',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='language',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='number_of_correct_answers',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='random',
        ),
    ]
