# Generated by Django 4.2.18 on 2025-03-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0011_shorttextmemorizationtests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortTextMemorizationTests',
            new_name='ShortTextMemorizationTest',
        ),
    ]
