# Generated by Django 4.2.1 on 2023-05-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0011_rename_challenges_challenge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gptissues',
            old_name='question',
            new_name='issue',
        ),
    ]
