# Generated by Django 4.2.18 on 2025-03-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_alter_shorttext_audio'),
        ('memorization', '0012_rename_shorttextmemorizationtests_shorttextmemorizationtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttextmemorizationtest',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.shorttext'),
        ),
    ]
