# Generated by Django 4.2.1 on 2023-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0012_rename_question_gptissues_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptissues',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
