# Generated by Django 4.2.6 on 2023-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0013_phrasemaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasemaker',
            name='translation_options',
            field=models.BooleanField(default=False),
        ),
    ]
