# Generated by Django 4.2.20 on 2025-07-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0013_shorttextmemorizationtest_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='number_of_correct_answers',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
