# Generated by Django 4.2.1 on 2023-05-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0022_terms_reference'),
        ('memorization', '0013_gptissues_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptissues',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='gpt_issues_tags', to='word.tags'),
        ),
    ]
