# Generated by Django 4.2.1 on 2023-05-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0014_gptissues_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='past_conjugation_irregular_verb',
            field=models.BooleanField(default=False),
        ),
    ]
