# Generated by Django 4.2.25 on 2025-10-31 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0014_historyattempt'),
        ('memorization', '0014_challenge_number_of_correct_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengesCompleted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.term')),
            ],
        ),
    ]
