# Generated by Django 4.2.25 on 2025-10-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0015_challengescompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicememorizationtestsoptions',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='options',
            name='word_memorization_random_test',
        ),
        migrations.RemoveField(
            model_name='shorttextmemorizationtest',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='unavailableitem',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='wordmemorizationrandomtest',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='wordmemorizationrandomtest',
            name='historic_challenge',
        ),
        migrations.RemoveField(
            model_name='wordmemorizationrandomtest',
            name='reference',
        ),
        migrations.DeleteModel(
            name='ChallengeShortText',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceMemorizationTestsOptions',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='ShortTextMemorizationTest',
        ),
        migrations.DeleteModel(
            name='UnavailableItem',
        ),
        migrations.DeleteModel(
            name='WordMemorizationRandomTest',
        ),
    ]
