# Generated by Django 4.2.6 on 2023-11-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0016_remove_translationgeneratorforsentence_sentences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationgeneratorforsentence',
            name='answer',
        ),
    ]
