# Generated by Django 4.2.25 on 2025-10-31 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0015_delete_historyattempt'),
        ('memorization', '0016_remove_multiplechoicememorizationtestsoptions_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('got_it_right', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('Portuguese', 'Portuguese'), ('English', 'English')], default='English', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.term')),
            ],
        ),
    ]
