# Generated by Django 4.2.1 on 2023-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0016_importtexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtexts',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
