# Generated by Django 4.2.6 on 2023-11-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_terms_language_alter_terms_text'),
        ('memorization', '0017_remove_translationgeneratorforsentence_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasemaker',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phrasemaker',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_phrase_maker', to='word.tags'),
        ),
    ]
