# Generated by Django 4.2.25 on 2025-10-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0017_historyattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyattempt',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge'),
        ),
    ]
