# Generated by Django 4.2.25 on 2025-11-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0018_historyattempt_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='hearing',
            field=models.BooleanField(default=False),
        ),
    ]
