# Generated by Django 4.2.1 on 2023-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0019_phrasegeneratorforterms_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptissues',
            name='profile',
            field=models.TextField(blank=True, default='You are an English teacher and will help me with grammar questions.', null=True),
        ),
    ]
