# Generated by Django 5.0.6 on 2025-11-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0019_challenge_hearing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricChallenge',
        ),
    ]
