# Generated by Django 4.2.1 on 2023-05-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0020_alter_gptissues_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasegeneratorforterms',
            name='profile',
            field=models.TextField(blank=True, default='You are an English teacher and will help me with grammar questions.', null=True),
        ),
    ]
