# Generated by Django 5.0.6 on 2025-11-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0020_delete_historicchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='phonetic_transcription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='translation',
            field=models.BooleanField(default=False),
        ),
    ]
