# Generated by Django 4.2.1 on 2023-05-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0021_phrasegeneratorforterms_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasegeneratorforterms',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
