# Generated by Django 4.2.6 on 2023-11-25 21:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0022_rename_term_multiplechoicememorizationtestsoptions_sentences_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicememorizationtestsoptions',
            name='sentences_options',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
