# Generated by Django 4.2.1 on 2023-06-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0023_extracttextfromvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtractTextFromVideo',
            new_name='ExtractTextFromPDF',
        ),
    ]
