# Generated by Django 4.2.6 on 2023-11-25 21:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0023_alter_multiplechoicememorizationtestsoptions_sentences_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicememorizationtests',
            name='sentences_options',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
