# Generated by Django 4.2.6 on 2023-11-26 02:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0024_alter_multiplechoicememorizationtests_sentences_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmemorizationrandomtest',
            name='sentences_options',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
