# Generated by Django 4.2.1 on 2023-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0024_rename_extracttextfromvideo_extracttextfrompdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasegeneratorforterms',
            name='base_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
