# Generated by Django 4.2.1 on 2023-06-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0025_phrasegeneratorforterms_base_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasegeneratorforterms',
            name='amount',
        ),
    ]
