# Generated by Django 4.2.1 on 2023-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0026_remove_phrasegeneratorforterms_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracttextfrompdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='./pdf'),
        ),
    ]
