# Generated by Django 4.2.6 on 2023-11-26 02:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_terms_language_alter_terms_text'),
        ('memorization', '0026_remove_multiplechoicememorizationtestsoptions_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceMemorizationTestsOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentences_options', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.terms')),
            ],
        ),
    ]
