# Generated by Django 4.2.1 on 2023-06-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0027_extracttextfrompdf_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasegeneratorforterms',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='phrasegeneratorforterms',
            name='base_text',
        ),
        migrations.RemoveField(
            model_name='phrasegeneratorforterms',
            name='profile',
        ),
    ]
