# Generated by Django 4.2.1 on 2023-06-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0028_remove_phrasegeneratorforterms_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrasegeneratorforterms',
            name='tags',
        ),
    ]
