# Generated by Django 4.2.1 on 2023-06-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0025_remove_terms_translations_translation_reference'),
        ('memorization', '0029_remove_phrasegeneratorforterms_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasegeneratorforterms',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='phrase_generator_for_terms', to='word.tags'),
        ),
    ]
