# Generated by Django 4.2.1 on 2023-06-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0030_phrasegeneratorforterms_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='past_conjugation_irregular_verb',
            new_name='phrases_associated_with_term',
        ),
    ]
