# Generated by Django 4.2.1 on 2023-06-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0031_rename_past_conjugation_irregular_verb_challenge_phrases_associated_with_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='multiple_translations',
            field=models.BooleanField(default=False),
        ),
    ]
