# Generated by Django 4.2.1 on 2023-06-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0025_remove_terms_translations_translation_reference'),
        ('memorization', '0033_verbsconjugation'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbsconjugation',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='word.tags'),
        ),
    ]
