# Generated by Django 4.2.1 on 2023-07-04 00:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0031_alter_terms_unique_together'),
        ('memorization', '0035_challenge_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='terms',
        ),
        migrations.CreateModel(
            name='Challengeterm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word.terms')),
            ],
        ),
    ]
