# Generated by Django 4.2.1 on 2023-07-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0031_alter_terms_unique_together'),
        ('memorization', '0036_remove_challenge_terms_challengeterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='terms',
            field=models.ManyToManyField(blank=True, null=True, related_name='challenges_terms', to='word.terms'),
        ),
        migrations.DeleteModel(
            name='Challengeterm',
        ),
    ]
