# Generated by Django 4.2.1 on 2023-07-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0039_rename_wordmemorizationtest_wordmemorizationrandomtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='audio',
            new_name='lissen',
        ),
        migrations.RenameField(
            model_name='wordmemorizationrandomtest',
            old_name='audio',
            new_name='lissen',
        ),
    ]
