# Generated by Django 4.2.1 on 2023-07-18 00:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0040_rename_audio_challenge_lissen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencesInOrderPrecedenceTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100)),
                ('term', models.TextField(blank=True, null=True)),
                ('lissen', models.FileField(blank=True, null=True, upload_to='')),
                ('answer', models.TextField(blank=True, null=True)),
                ('hit_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorization.challenge')),
            ],
        ),
    ]
