# Generated by Django 4.2.1 on 2023-07-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0041_sentencesinorderprecedencetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeterm',
            name='sequence_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
